# Generated by Django 6.0.5 on 2026-06-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('meio_contato_1', models.CharField(blank=True, max_length=50)),
                ('contato_1', models.CharField(blank=True, max_length=150)),
                ('meio_contato_2', models.CharField(blank=True, max_length=50)),
                ('contato_2', models.CharField(blank=True, max_length=150)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('meio_contato_1', models.CharField(blank=True, max_length=50)),
                ('contato_1', models.CharField(blank=True, max_length=150)),
                ('meio_contato_2', models.CharField(blank=True, max_length=50)),
                ('contato_2', models.CharField(blank=True, max_length=150)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidade_preco', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='cadastros.categoriamaterial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='cadastros.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=150)),
                ('unidade', models.CharField(blank=True, max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='cadastros.material')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('tipo_servico', models.CharField(blank=True, max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastros.cliente')),
            ],
        ),
    ]
