# Generated by Django 6.0.5 on 2026-06-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('potencia_kva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Potência (kVA)')),
                ('tensao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tensão')),
                ('polos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Polos')),
                ('frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Frequência (Hz)')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('simbolo', models.CharField(max_length=20, unique=True, verbose_name='Símbolo')),
                ('grandeza', models.CharField(max_length=50, verbose_name='Grandeza')),
                ('fator_base', models.DecimalField(decimal_places=10, default=1, max_digits=20, verbose_name='Fator para unidade base')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterModelOptions(
            name='categoriamaterial',
            options={'verbose_name': 'Categoria de Material', 'verbose_name_plural': 'Categorias de Material'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Matéria Prima', 'verbose_name_plural': 'Matérias Primas'},
        ),
        migrations.AlterModelOptions(
            name='materialpropriedade',
            options={'verbose_name': 'Propriedade do Material', 'verbose_name_plural': 'Propriedades dos Materiais'},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade_preco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidademedida'),
        ),
    ]
