# Generated by Django 6.0.5 on 2026-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_maquina_unidademedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fabricante',
            field=models.CharField(max_length=150, null=True, verbose_name='Fabricante'),
        ),
    ]
