# Generated by Django 6.0.5 on 2026-06-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_maquina_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='cadastros.maquina'),
        ),
    ]
