# Generated by Django 6.0.5 on 2026-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_ordemservico_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='polos',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='tensao',
        ),
        migrations.AddField(
            model_name='maquina',
            name='corrente_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Corrente (A)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='corrente_excitatriz_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Corrente da excitatriz (A)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='excitatriz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Excitatriz'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='fator_potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fator de potência'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='frequencia_hz',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=8, verbose_name='Frequência (Hz)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='numero_polos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de polos'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='numero_serie',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nº de série'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='rotacao_rpm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rotação (rpm)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tensao_excitatriz_v',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tensão da excitatriz (V)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tensao_v',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tensão (V)'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='vertical', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registro'),
        ),
    ]
