# Generated by Django 6.0.5 on 2026-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_maquina_fabricante_remove_maquina_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='numero_serie',
            field=models.CharField(default='SEM_SERIE', max_length=100, unique=True, verbose_name='Nº de série'),
            preserve_default=False,
        ),
    ]
