# Generated by Django 6.0.5 on 2026-06-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_maquina_numero_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEstator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bobinas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de bobinas')),
                ('numero_condutores_por_espira', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº cond./espira')),
                ('numero_espiras_por_bobina', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de espiras/bobina')),
                ('numero_series', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº séries')),
                ('tipo_condutor', models.CharField(blank=True, max_length=100, verbose_name='Tipo condutor')),
                ('numero_elementos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de elementos')),
                ('numero_saidas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº saídas')),
                ('numero_paralelos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº paralelo')),
                ('tipo_ligacao', models.CharField(blank=True, max_length=20, verbose_name='Tipo de ligação')),
                ('numero_sensores', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº sensor')),
                ('tipo_cunha', models.CharField(blank=True, max_length=100, verbose_name='Tipo de cunha')),
                ('passo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Passo')),
                ('tipo_sensor', models.CharField(blank=True, max_length=100, verbose_name='Tipo de sensor')),
                ('local_sensor', models.CharField(blank=True, max_length=100, verbose_name='Local do sensor')),
                ('peso_cobre_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso cobre total')),
                ('peso_bobina', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso bobina')),
                ('area_espira', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área da espira')),
                ('comprimento_nucleo_magnetico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comprimento do núcleo magnético')),
                ('numero_canais_ventilacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº canais de ventilação')),
                ('diametro_interno_nucleo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diâmetro interno do núcleo')),
                ('diametro_externo_nucleo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diâmetro externo do núcleo')),
                ('diametro_rotor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diâmetro do rotor')),
                ('entreferro_gerador', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Entreferro do gerador')),
                ('cor_estator', models.CharField(blank=True, max_length=50, verbose_name='Cor do estator')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_estator', to='cadastros.maquina')),
            ],
        ),
    ]
