# Generated by Django 6.0.5 on 2026-06-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_dadosestator'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente'),
            preserve_default=False,
        ),
    ]
