# Generated by Django 6.0.5 on 2026-06-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_maquina_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente',null=True,blank=True,related_name='maquinas'),
        ),
    ]
