# Generated by Django 6.0.5 on 2026-06-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_maquina_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='cadastros.cliente'),
        ),
    ]
