# Generated by Django 6.0.5 on 2026-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_maquina_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosestator',
            name='tipo_bobina',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo bobina'),
        ),
        migrations.AddField(
            model_name='dadosestator',
            name='tipo_bobinado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo bobinado'),
        ),
    ]
