# Generated by Django 6.0.5 on 2026-06-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_dadosestator_tipo_bobina_dadosestator_tipo_bobinado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosestator',
            options={'verbose_name': 'Dados do Estator', 'verbose_name_plural': 'Dados do Estator'},
        ),
    ]
