# Generated by Django 6.0.5 on 2026-06-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_dadosestator_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPerifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aro_amarracao_ll', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aro de amarração LL')),
                ('aro_amarracao_lol', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aro de amarração LOL')),
                ('material_aro_ll', models.CharField(blank=True, max_length=150, verbose_name='Material LL')),
                ('material_aro_lol', models.CharField(blank=True, max_length=150, verbose_name='Material LOL')),
                ('calco_amarracao_inferior_ll', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calço amarração inferior LL')),
                ('calco_amarracao_inferior_lol', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calço amarração inferior LOL')),
                ('calco_amarracao_superior_ll', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calço amarração superior LL')),
                ('calco_amarracao_superior_lol', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calço amarração superior LOL')),
                ('material_calcos', models.CharField(blank=True, max_length=150, verbose_name='Material dos calços')),
                ('campo_eletrico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Campo elétrico')),
                ('densidade_corrente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Densidade de corrente')),
                ('classe_termica_cabo', models.CharField(blank=True, max_length=100, verbose_name='Classe térmica do cabo')),
                ('area_cabo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área do cabo')),
                ('comprimento_cabo_interno', models.CharField(blank=True, max_length=100, verbose_name='Comprimento do cabo interno')),
                ('comprimento_cabo_externo', models.CharField(blank=True, max_length=100, verbose_name='Comprimento do cabo externo')),
                ('descricao_terminal', models.CharField(blank=True, max_length=150, verbose_name='Descrição do terminal')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_perifericos', to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Dados Periféricos',
                'verbose_name_plural': 'Dados Periféricos',
            },
        ),
    ]
