# Generated by Django 6.0.5 on 2026-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_dadosperifericos_obs_calco_amarracao_inferior_ll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosperifericos',
            name='obs_calco_amarracao_superior_lol',
            field=models.CharField(blank=True, max_length=150, verbose_name='Observação'),
        ),
    ]
