# Generated by Django 6.0.5 on 2026-06-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_dadosperifericos_obs_calco_amarracao_superior_lol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosConstrutivosBobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('croqui_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croqui_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croqui_i', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croqui_j', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croqui_k', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croqui_l', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_a1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_a2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_b1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_b2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_c1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_c2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_d1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amarracao_d2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_a1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_a2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_b1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_b2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_c1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_c2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_d1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('configuracao_d2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_e1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_e2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montada_f_sem_isolacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bobina', to='cadastros.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='DadosGeometricosMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ranhura', models.CharField(blank=True, max_length=50)),
                ('ranhura_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranhura_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranhura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranhura_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranhura_e', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ranhura_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bobina_e', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bobina_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bobina_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bobina_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condutor_e', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condutor_f', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condutor_E_iso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condutor_F_iso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_calco', models.CharField(blank=True, max_length=50)),
                ('calco_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calco_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calco_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calco_d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_geometricos', to='cadastros.maquina')),
            ],
        ),
    ]
