# Generated by Django 6.0.5 on 2026-06-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_dadosconstrutivosbobina_dadosgeometricosmaquina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosgeometricosmaquina',
            old_name='condutor_E_iso',
            new_name='condutor_E_iso',
        ),
        migrations.RenameField(
            model_name='dadosgeometricosmaquina',
            old_name='condutor_F_iso',
            new_name='condutor_F_iso',
        ),
    ]
