# Generated by Django 6.0.5 on 2026-06-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_rename_condutor_e_dadosgeometricosmaquina_condutor_e_iso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato_1',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato_2',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='meio_contato_1',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='meio_contato_2',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='site',
            field=models.URLField(blank=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
