# Generated by Django 6.0.5 on 2026-06-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_remove_fornecedor_contato_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='prioridade',
            field=models.PositiveIntegerField(blank=True, max_length=1, null=True),
        ),
    ]
