# Generated by Django 6.0.5 on 2026-06-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_material_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
