# Generated by Django 6.0.5 on 2026-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_material_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_material',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='prioridade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
