# Generated by Django 6.0.5 on 2026-06-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_material_codigo_material_alter_material_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidade_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidademedida'),
        ),
    ]
