# Generated by Django 6.0.5 on 2026-06-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_alter_material_unidade_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaisBobinagemRoebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobressalente_bobinas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('coeficiente_seguranca_bobinas', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('aros_amarracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('barramentos_ligacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('cadarco_fibra_vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('calcos_radiais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('calcos_tangenciais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('conexoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('consolidacao_condutores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('cunhagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('fita_acabamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('fita_condutiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('fita_sacrificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('fita_semicondutiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('isolacao_condutores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('isolacao_panqueca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('isolacao_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_bobinagem_roebel', to='cadastros.maquina')),
                ('massa_enchimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('pavio_central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('verniz_condutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
                ('verniz_semicondutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.material')),
            ],
            options={
                'verbose_name': 'Materiais Bobinagem Roebel',
                'verbose_name_plural': 'Materiais Bobinagem Roebel',
            },
        ),
    ]
