# Generated by Django 6.0.5 on 2026-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_materiaisbobinagemroebel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_material',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
