# Generated by Django 6.0.5 on 2026-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_alter_material_codigo_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosperifericos',
            name='area_cabo',
        ),
        migrations.AddField(
            model_name='dadosperifericos',
            name='tensao_cabo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tensão do cabo'),
        ),
        migrations.AlterField(
            model_name='dadosestator',
            name='tipo_bobina',
            field=models.CharField(blank=True, choices=[('barra_roebel', 'Barras Roebel'), ('multiespiras', 'Bobinas Multiespiras')], max_length=100, verbose_name='Tipo bobina'),
        ),
        migrations.AlterField(
            model_name='dadosestator',
            name='tipo_bobinado',
            field=models.CharField(blank=True, choices=[('ondulado', 'Ondulado'), ('imbricado', 'Imbricado')], max_length=100, verbose_name='Tipo bobinado'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='bobina_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='e'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='bobina_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='f'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='bobina_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='g'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='bobina_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='h'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='calco_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='calco_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='calco_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='calco_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='condutor_E_iso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='condutor_F_iso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='condutor_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='e'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='condutor_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='f'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='d'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='e'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='ranhura_f',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='f'),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='tipo_calco',
            field=models.CharField(blank=True, choices=[('calco1', 'Tipo 1'), ('calco2', 'Tipo 2'), ('calco3', 'Tipo 3'), ('calco4', 'Tipo 4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='tipo_ranhura',
            field=models.CharField(blank=True, choices=[('ranhura1', 'Tipo 1'), ('ranhura2', 'Tipo 2'), ('ranhura3', 'Tipo 3')], max_length=50),
        ),
    ]
