# Generated by Django 6.0.6 on 2026-06-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_remove_dadosperifericos_area_cabo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dados_maquina', to='cadastros.cliente'),
        ),
        migrations.CreateModel(
            name='ResIsolamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensao', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('temperatura', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('umidade', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tempo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø01xm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø02xm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø03xm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø04xm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('res_ohmica_t', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø01', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø02', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Ø03', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resistencia_isolamento', to='cadastros.maquina')),
            ],
            options={
                'verbose_name': 'Resistência de isolamento',
                'verbose_name_plural': 'Resistências de isolamento',
            },
        ),
    ]
