# Generated by Django 6.0.6 on 2026-06-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_alter_maquina_cliente_resisolamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaisbobinagemroebel',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bobinagem_roebel', to='cadastros.maquina'),
        ),
        migrations.AlterField(
            model_name='resisolamento',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_ensaios', to='cadastros.maquina'),
        ),
    ]
