# Generated by Django 6.0.5 on 2026-06-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_alter_materiaisbobinagemroebel_maquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterialParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descrição / Nome')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('lista', 'Lista'), ('checkbox', 'Checkbox')], max_length=20, verbose_name='Tipo')),
                ('grandeza', models.CharField(blank=True, max_length=50, verbose_name='Grandeza')),
                ('inteiro', models.BooleanField(default=False, verbose_name='Valor inteiro')),
                ('usar_limites', models.BooleanField(default=False, verbose_name='Usar valor mín. e máx.')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Valor mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Valor máximo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='cadastros.categoriamaterial')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidademedida')),
            ],
            options={
                'verbose_name': 'Parâmetro da Categoria',
                'verbose_name_plural': 'Parâmetros das Categorias',
                'ordering': ('categoria', 'ordem', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='CategoriaMaterialParametroOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Opção')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cadastros.categoriamaterialparametro')),
            ],
            options={
                'verbose_name': 'Opção do Parâmetro',
                'verbose_name_plural': 'Opções dos Parâmetros',
                'ordering': ('parametro', 'ordem', 'nome'),
            },
        ),
    ]
