# Generated by Django 6.0.6 on 2026-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_categoriamaterialparametro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grandeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Grandeza',
                'verbose_name_plural': 'Grandezas',
                'ordering': ('nome',),
            },
        ),
    ]
