# Generated by Django 6.0.6 on 2026-06-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_grandeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandeza',
            name='unidade_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.unidademedida'),
        ),
    ]
