# Generated by Django 6.0.6 on 2026-06-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_grandeza_unidade_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidademedida',
            name='grandeza_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='cadastros.grandeza'),
        ),
    ]
