# Generated by Django 6.0.6 on 2026-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_unidademedida_grandeza_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='grandeza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grandeza'),
        ),
    ]
