# Generated by Django 6.0.6 on 2026-06-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_alter_unidademedida_grandeza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidademedida',
            name='grandeza',
        ),
        migrations.RemoveField(
            model_name='unidademedida',
            name='grandeza_fk',
        ),
    ]
