# Generated by Django 6.0.6 on 2026-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_remove_unidademedida_grandeza_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialPropriedade',
        ),
    ]
