# Generated by Django 6.0.6 on 2026-06-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_delete_materialpropriedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialParametroValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.CharField(blank=True, max_length=255, verbose_name='Valor texto')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Valor numérico')),
                ('valor_booleano', models.BooleanField(blank=True, null=True, verbose_name='Valor booleano')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_tecnicos', to='cadastros.material')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_materiais', to='cadastros.categoriamaterialparametro')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valores_parametros', to='cadastros.unidademedida')),
            ],
            options={
                'verbose_name': 'Valor Técnico do Material',
                'verbose_name_plural': 'Valores Técnicos dos Materiais',
                'unique_together': {('material', 'parametro')},
            },
        ),
    ]
