# Generated by Django 6.0.6 on 2026-06-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_materialparametrovalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamaterialparametro',
            name='grandeza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_material', to='cadastros.grandeza'),
        ),
    ]
