# Generated by Django 6.0.6 on 2026-06-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_alter_categoriamaterialparametro_grandeza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialparametrovalor',
            name='observacoes',
            field=models.CharField(blank=True, verbose_name='Observações'),
        ),
    ]
