# Generated by Django 6.0.6 on 2026-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_alter_materialparametrovalor_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosconstrutivosbobina',
            name='croqui_ponta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
