# Generated by Django 6.0.6 on 2026-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_rename_croqui_j_dadosconstrutivosbobina_croqui_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosgeometricosmaquina',
            name='folga_ranhura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Folga na ranhura'),
        ),
    ]
