# Generated by Django 6.0.6 on 2026-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_dadosgeometricosmaquina_folga_ranhura'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosgeometricosmaquina',
            name='sobreposicao_isolante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='h'),
        ),
    ]
