# Generated by Django 6.0.6 on 2026-08-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_dadosgeometricosmaquina_sobreposicao_isolante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosgeometricosmaquina',
            name='sobreposicao_isolante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sobreposição da fita Isolante'),
        ),
    ]
