# Generated by Django 6.0.6 on 2026-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_alter_dadosgeometricosmaquina_sobreposicao_isolante'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamaterial',
            name='identificador',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='identificador',
            field=models.TextField(blank=True, max_length=4, verbose_name='Identificador'),
        ),
    ]
