# Generated by Django 6.0.6 on 2026-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0043_categoriamaterial_identificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='identificador',
            field=models.CharField(blank=True, max_length=4, verbose_name='Identificador'),
        ),
    ]
