# Generated by Django 6.0.6 on 2026-08-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0044_alter_fornecedor_identificador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ensaio')),
                ('norma_referencia', models.CharField(blank=True, max_length=100, verbose_name='Norma de Referência (Ex: IEEE 43)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Procedimento')),
            ],
            options={
                'verbose_name': 'Tipo de Ensaio',
                'verbose_name_plural': 'Tipos de Ensaios',
            },
        ),
        migrations.CreateModel(
            name='RegistroEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(verbose_name='Data e Hora da Realização')),
                ('resultado_geral', models.CharField(choices=[('AP', 'Aprovado'), ('RP', 'Reprovado'), ('AR', 'Aprovado com Ressalvas'), ('AN', 'Apenas Análise/Coleta')], default='AN', max_length=2, verbose_name='Resultado Geral')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Técnicas')),
                ('laudo_anexo', models.FileField(blank=True, null=True, upload_to='ensaios/laudos/%Y/%m/', verbose_name='Laudo / Relatório (PDF)')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensaios_realizados', to='cadastros.maquina')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensaios_da_os', to='cadastros.ordemservico')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Técnico')),
                ('tipo_ensaio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='ensaios.tipoensaio')),
            ],
            options={
                'verbose_name': 'Registro de Ensaio',
                'verbose_name_plural': 'Registros de Ensaios',
                'ordering': ['-data_realizacao'],
            },
        ),
    ]
