# Generated by Django 6.0.6 on 2026-08-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensaios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBumpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_impacto', models.CharField(help_text='Ex: Cabeça de bobina lado acoplado - Fase U, Posição 12h', max_length=100, verbose_name='Local do Impacto/Medição')),
                ('frequencia_natural_hz', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Frequência Natural 1 (Hz)')),
                ('frequencia_natural_2_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Frequência Natural 2 (Hz)')),
                ('amortecimento_porcentagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fator de Amortecimento (%)')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bump_test', to='ensaios.registroensaio')),
            ],
            options={
                'verbose_name': 'Dados de Bump Test',
                'verbose_name_plural': 'Dados de Bump Tests',
            },
        ),
        migrations.CreateModel(
            name='DadosSurgeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensao_pico_volts', models.PositiveIntegerField(verbose_name='Tensão de Pico Aplicada (V)')),
                ('ear_porcentagem', models.DecimalField(blank=True, decimal_places=2, help_text='Diferença percentual de área entre as formas de onda.', max_digits=5, null=True, verbose_name='EAR - Error Area Ratio (%)')),
                ('analise_onda', models.CharField(choices=[('SIM', 'Ondas Simétricas / Sobrepostas'), ('ASS', 'Ondas Assimétricas / Deslocadas'), ('CUR', 'Curto-circuito detectado')], max_length=3, verbose_name='Análise da Forma de Onda')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_surge_test', to='ensaios.registroensaio')),
            ],
            options={
                'verbose_name': 'Dados de Surge Test',
                'verbose_name_plural': 'Dados de Surge Tests',
            },
        ),
        migrations.CreateModel(
            name='DadosTensaoAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_testada', models.CharField(help_text='Ex: Fase U contra Carcaça, Fases U+V+W contra Carcaça', max_length=50, verbose_name='Fase/Circuito Testado')),
                ('tensao_ensaio_volts', models.PositiveIntegerField(verbose_name='Tensão de Ensaio (V)')),
                ('tempo_aplicacao_segundos', models.PositiveIntegerField(default=60, verbose_name='Tempo de Aplicação (s)')),
                ('corrente_fuga_ma', models.DecimalField(decimal_places=3, help_text='Corrente de fuga medida ao final do tempo estabilizado.', max_digits=8, verbose_name='Corrente de Fuga (mA)')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_tensao_aplicada', to='ensaios.registroensaio')),
            ],
            options={
                'verbose_name': 'Dados de Tensão Aplicada',
                'verbose_name_plural': 'Dados de Tensão Aplicada',
            },
        ),
    ]
