# Generated by Django 6.0.6 on 2026-08-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensaios', '0002_dadosbumptest_dadossurgetest_dadostensaoaplicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosLoopTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dutos_ar', models.PositiveIntegerField(default=0, verbose_name='Número de Dutos de Ar')),
                ('altura_duto_ar_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Altura do Duto de Ar (mm)')),
                ('fator_empilhamento', models.DecimalField(decimal_places=2, help_text='Ex: 0.95', max_digits=3, verbose_name='Fator de Empilhamento do Núcleo')),
                ('densidade_especifica_laminacao', models.DecimalField(decimal_places=2, help_text='Geralmente 7.65 kg/dm³ para aço silício.', max_digits=4, verbose_name='Densidade Específica da Laminação (kg/dm³)')),
                ('diametro_furos_chapa_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Diâmetro dos Furos na Chapa (mm)')),
                ('numero_furos_chapa', models.PositiveIntegerField(default=0, verbose_name='Número de Furos na Chapa')),
                ('densidade_fluxo_nominal_t', models.DecimalField(decimal_places=2, help_text='Valor alvo para o ensaio (Ex: 1.0 ou 1.4 Tesla)', max_digits=4, verbose_name='Densidade de Fluxo Nominal (Tesla)')),
                ('perdas_especificas_chapa', models.DecimalField(decimal_places=2, help_text='Referência do fabricante para a chapa siliciosa tipo A', max_digits=5, verbose_name='Perdas Específicas da Chapa (W/kg)')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_loop_test', to='ensaios.registroensaio')),
            ],
            options={
                'verbose_name': 'Dados de Loop Test',
                'verbose_name_plural': 'Dados de Loop Tests',
            },
        ),
    ]
