# Generated by Django 6.0.6 on 2026-10-04 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_tt', models.CharField(max_length=10, verbose_name='Nº do Item (TT)')),
                ('titulo_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 3 (Opcional)')),
                ('criado_por', models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=50, unique=True, verbose_name='Ordem de Serviço (OS - YYYY)')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da OS')),
                ('criado_por', models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('RT', 'Relatório técnico'), ('DT', 'Desenho técnico'), ('CRO', 'Cronograma'), ('PRO', 'Procedimento'), ('PO.PRO', 'Procedimento da produção'), ('IT.PRO', 'Instrução de trabalho da produção'), ('LM', 'Lista de Materiais'), ('PIT', 'Plano de Inspeção e teste'), ('DB', 'DataBook'), ('MC', 'Memorial de cálculo')], max_length=20, verbose_name='Tipo de Documento (XXX)')),
                ('criado_por', models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por')),
                ('esconder_titulo_2', models.BooleanField(default=False, verbose_name='Ocultar Título 2')),
                ('esconder_titulo_3', models.BooleanField(default=False, verbose_name='Ocultar Título 3')),
                ('status', models.CharField(choices=[('Não iniciado', 'Não iniciado'), ('Em elaboração', 'Em elaboração'), ('Em revisão', 'Em revisão'), ('Aprovado', 'Aprovado'), ('Em fabricação', 'Em fabricação'), ('Cancelado', 'Cancelado')], default='Não iniciado', max_length=30, verbose_name='Status do Documento')),
                ('revisao', models.CharField(choices=[('R00', 'R00'), ('R01', 'R01'), ('R02', 'R02'), ('R03', 'R03'), ('R04', 'R04'), ('R05', 'R05'), ('R06', 'R06'), ('R07', 'R07'), ('R08', 'R08'), ('R09', 'R09'), ('R10', 'R10'), ('R11', 'R11'), ('R12', 'R12'), ('R13', 'R13'), ('R14', 'R14'), ('R15', 'R15'), ('R16', 'R16'), ('R17', 'R17'), ('R18', 'R18'), ('R19', 'R19'), ('R20', 'R20')], default='R00', max_length=5, verbose_name='Revisão Atual (XX)')),
                ('responsavel', models.CharField(blank=True, choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, null=True, verbose_name='Responsável')),
                ('data_emissao_inicial', models.DateField(blank=True, null=True, verbose_name='Data de Emissão Inicial')),
                ('data_emissao_final', models.DateField(blank=True, null=True, verbose_name='Data de Emissão Final')),
                ('caminho_editavel', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do editável')),
                ('caminho_pdf', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do PDF')),
                ('caminho_adicional', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho adicional')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='organizador.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_vv', models.CharField(max_length=10, verbose_name='Nº do Conjunto (VV)')),
                ('titulo_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 1 (Nome do Conjunto)')),
                ('disciplina', models.CharField(choices=[('GER', 'Geral'), ('MEC', 'Mecânica')], default='MEC', max_length=10, verbose_name='Disciplina')),
                ('criado_por', models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='organizador.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'unique_together': {('os', 'acronimo_vv')},
            },
        ),
        migrations.CreateModel(
            name='Subconjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo_uu', models.CharField(max_length=10, verbose_name='Nº do Subconjunto (UU)')),
                ('titulo_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título 2 (Opcional)')),
                ('criado_por', models.CharField(choices=[('Rebeca Palma', 'Rebeca Palma'), ('Marcello Neto', 'Marcello Neto'), ('Bruno Romano', 'Bruno Romano'), ('Fábio Watanabe', 'Fábio Watanabe')], max_length=50, verbose_name='Criado por')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subconjuntos', to='organizador.conjunto', verbose_name='Conjunto')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subconjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='organizador.subconjunto', verbose_name='Subconjunto'),
        ),
    ]
