# Generated by Django 6.0.6 on 2026-10-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_alter_fornecedor_identificador'),
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Organização de OS', 'verbose_name_plural': 'Organizações de OS'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='numero_os',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ordem_cadastros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_organizador', to='cadastros.ordemservico', verbose_name='Ordem de Serviço Oficial'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='criado_por',
            field=models.CharField(blank=True, max_length=50, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição da OS'),
        ),
    ]
